string $fileDialog = `file -q -sn`;
if(`gmatch $fileDialog "*lr*"`)
{
;
}
else
{error  "File name is wrong!";}


source SetMentalrayRenderSetting;

//string $renderPass[] = `listTransforms "-type mesh"`;
//string $renderObj;
//for($renderObj in $renderPass)
//{
//setAttr ($renderObj+".primaryVisibility") 1;
//}
select -cl;

string $regularExpr = "lr_.*_f";
string $saveAsname = `substitute $regularExpr $fileDialog "lr_rgb_f"`;
file  -rename $saveAsname;
file -f -save;
